---
title: "Tools"
format: html
---

<div class="section-label">Section · Tools</div>

## Software used in HYDRA-EO tutorials

This page summarises the main R packages and tools used in the tutorials, with links to their Git repositories and simple usage examples.

::: {.card-grid}

::: {.vbl-card}
<div class="pill-mini">R · ToolsRTM</div>
### Canopy & leaf RTMs
ToolsRTM package provides a unified suite of radiative transfer models for simulating leaf, canopy and soil reflectance across multiple sensor resolutions. It integrates PROSPECT, FLUSPECT, Liberty, INFORM, fourSAIL and PROSAIL for detailed optical simulations and advance modelling as SPART and MARMIT for soil. These capabilities support flexible, physics-based workflows for EO data analysis and model–data integration.

GitLab: <a href="https://gitlab.com/caminoccg/toolsrtm" target="_blank" rel="noopener">ToolsRTM</a>
:::

::: {.vbl-card}
<div class="pill-mini">R · SCOPEinR</div>

### Energy balance & SIF

SCOPEinR implements the SCOPE model for simulating soil–canopy radiative transfer, photosynthesis, fluorescence and surface energy balance. It provides an R interface for producing consistent reflectance, SIF and photosynthesis products under varying stress, physiological and illumination conditions. This package supports detailed modelling of vegetation functioning in crop studies.

GitLab: <a href="https://gitlab.com/caminoccg/scopeinr" target="_blank" rel="noopener">SCOPEinR</a>
:::

:::


  <div class="text-center small text-secondary vbl-footer-classic">
  <div class="vbl-footer-line"></div>
  <p class="mb-1">© 2026 HYDRA-EO.</p>
  <p class="mb-2">HYDRA-EO is funded by the European Space Agency (ESA) 
    under the EXPRO+ Tender “Crop Multiple Stressors, Pests and Diseases”</p>
  <p class="mb-3">Action 1-12684.</p>
  <p class="mb-4">
    Source repository:
    <a href="https://ccgcam.github.io/HydraEO/" target="_blank" rel="noopener">
      HYDRA-EO pipeline
    </a>
  </p>
</div>
